root: true
env:
  node: true
extends:
  - "@chookslint/eslint-config-typescript/strict"
  - "@chookslint/eslint-config-typescript/types"
parserOptions:
  project: true
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: "*.js"
    extends:
      - "@chookslint/eslint-config-typescript"
